apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pkdev-deployment
spec:
  selector:
    matchLabels:
      app: pkdev-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: pkdev-devops-project
    spec:
      containers:
      - name: pkdev-devops-project
        image: pndrns/simple-devops-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pkdev-service
  labels:
    app: pkdev-devops-project
spec:
  selector:
    app: pkdev-devops-project
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      
